import os

GITHUB_WEBHOOK_SECRET = os.environ.get('GITHUB_WEBHOOK_SECRET')
CONTRIBUTION_ACCEPTED_TOPIC = os.environ.get('CONTRIBUTION_ACCEPTED_TOPIC')
assert GITHUB_WEBHOOK_SECRET and CONTRIBUTION_ACCEPTED_TOPIC
