import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass

GITHUB_WEBHOOK_SECRET = os.environ.get('GITHUB_WEBHOOK_SECRET')
CONTRIBUTION_ACCEPTED_TOPIC = os.environ.get('CONTRIBUTION_ACCEPTED_TOPIC')
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN')
assert GITHUB_WEBHOOK_SECRET and CONTRIBUTION_ACCEPTED_TOPIC and GITHUB_TOKEN
