# Generated by Django 4.1.1 on 2022-09-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar_url', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('consider_contributions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('merged', models.BooleanField(default=False)),
                ('labels', models.ManyToManyField(to='leaderboard.label')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.githubuser')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('locked', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('labels', models.ManyToManyField(to='leaderboard.label')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.githubuser')),
            ],
        ),
    ]
