# Generated by Django 4.1.1 on 2022-10-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='leaderboard.githubuser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=255),
        ),
    ]
