# Generated by Django 4.1.1 on 2022-10-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_issue_assignee_alter_issue_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_opening_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.pullrequest'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merge_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='merged',
            field=models.BooleanField(),
        ),
    ]
