# Generated by Django 4.1.1 on 2022-10-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_issue_html_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='html_url',
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='html_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
