# Generated by Django 4.1.1 on 2022-10-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0005_remove_issue_html_url_pullrequest_html_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pullrequest",
            name="labels",
        ),
    ]
